all:
  vars:
    ansible_host: localhost
    ansible_user: crypt
    ansible_pass: d00m
    ansible_become_pass: d00m
  children:
    docker:
      children:
        gitlab:
          hosts:
            gitlab01:
        ldap:
          hosts:
            ldap01:
        librenms:
          hosts:
            librenms01:
        mariadb:
          hosts:
            mariadb01:
        minio:
          hosts:
            minio01:
        netbox:
          hosts:
            netbox01:
        nomad:
          children:
            nomad_server:
              hosts:
                nomad-srv01:
                nomad-srv02:
                nomad-srv03:
            nomad_client:
              hosts:
                nomad-client01:
                nomad-client02:
        openbao:
          hosts:
            openbao01:
        postgres:
          hosts:
            postgres01:
        powerdns:
          hosts:
            powerdns01:
        radius:
          hosts:
            radius01:
        tacacs:
          hosts:
            tacacs01:
        zabbix:
          hosts:
            zabbix01:
        zabbix_testhost:
          hosts:
            zabbix-testhost01:
        snmpv3_testhost:
          vars:
            docker_snmpv3_testhost:
              network:
                name: zabbix_zabbix
                external: true
          hosts:
            snmpv3-testhost01:
        network_device_emulator:
          vars:
            docker_network_device_emulator:
              network:
                name: zabbix_zabbix
                external: true
          hosts:
            network-device-emulator01:
