---
- name: Restart docker zabbix compose
  ansible.builtin.systemd:
    name: docker-zabbix
    state: restarted
    daemon_reload: true
  when:
    - docker_zabbix.apply | bool
    - not ansible_check_mode
