---
- name: Restart docker librenms compose
  ansible.builtin.systemd:
    name: docker-librenms
    state: restarted
    daemon_reload: true
  when:
    - docker_librenms.apply | bool
    - not ansible_check_mode
