---
docker_network_device_emulator:
  project_name: network-device-emulator
  project_dir: /opt/docker/network-device-emulator
  docker_binary: /usr/bin/docker
  apply: true
  pull_policy: always
  build: always
  recreate: auto
  remove_orphans: true
  wait: false
  wait_timeout: null
  restart: unless-stopped

  image_name: tmnt/network-device-emulator
  base_image: python:3.12-alpine
  data_dir: /opt/docker/network-device-emulator/data
  healthcheck_oid: 1.3.6.1.2.1.1.6.0

  network:
    name: zabbix_zabbix
    external: true

  devices:
    cisco-ios01:
      host_port: 2161
      community: cisco
      sysdescr: Cisco IOS Software, C2960 Software mock
      sysobjectid: 1.3.6.1.4.1.9.1.1208
      interfaces:
        - index: 1
          descr: GigabitEthernet0/1
          type: 6
          speed: 1000000000
          oper_status: 1
        - index: 2
          descr: GigabitEthernet0/2
          type: 6
          speed: 1000000000
          oper_status: 2
    huawei-vrp01:
      host_port: 2162
      community: huawei
      sysdescr: Huawei Versatile Routing Platform Software mock
      sysobjectid: 1.3.6.1.4.1.2011.2.23.662
      interfaces:
        - index: 1
          descr: GE0/0/1
          type: 6
          speed: 1000000000
          oper_status: 1
    hp-comware01:
      host_port: 2163
      community: hp
      sysdescr: HP Comware mock
      sysobjectid: 1.3.6.1.4.1.25506.1.260
      interfaces:
        - index: 1
          descr: GigabitEthernet1/0/1
          type: 6
          speed: 1000000000
          oper_status: 1
    zte-zxros01:
      host_port: 2164
      community: zte
      sysdescr: ZTE ZXROS mock
      sysobjectid: 1.3.6.1.4.1.3902.1082
      interfaces:
        - index: 1
          descr: gei-0/1/0/1
          type: 6
          speed: 1000000000
          oper_status: 1
