---
galaxy_info:
  role_name: docker_zabbix_testhost
  author: tmnt-lab
  description: Run configurable Zabbix agent2 mock test hosts using Docker Compose.
  license: MIT
  min_ansible_version: "2.15"
dependencies: []
